In [23]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as st

# The class, the object, the data and the methods

## Defining the class

In [63]:
class CountryLevelDataAnalysis:
    def loading_country_level_predictors(self):
        self.predictors = pd.read_csv('./country_level_processed_data/country_predictors.csv')
        
    def loading_country_level_correlations(self):
        self.correlations = pd.read_csv('./country_level_processed_data/country_correlations.csv')
        
    def renaming_country_column(self):
        self.correlations.columns = ['iso_numeric', 'freedom_socialism', 'freedom_family', 'freedom_ethnicity', 'freedom_gender', 'freedom_nationalism', 'freedom_religiosity',
        'socialism_family', 'socialism_ethnicity', 'socialism_gender', 'socialism_nationalism', 'socialism_religiosity', 
        'family_ethnicity', 'family_gender', 'family_nationalism', 'family_religiosity', 
        'ethnicity_gender', 'ethnicity_nationalism', 'ethnicity_religiosity', 
        'gender_nationalism', 'gender_religiosity', 
        'nationalism_religiosity']
        
    def merging_data_frames(self):
        self.predictors_correlations = pd.merge(self.predictors, self.correlations, on ='iso_numeric')
        
    def saving_merged_data(self):
        self.predictors_correlations.to_csv('./country_level_processed_data/predictors_correlations.csv', sep=',', index=True, encoding='utf-8')
        
    def regression_sklearn(self):
        self.correlation_names = ['freedom_socialism', 'freedom_family', 'freedom_ethnicity', 'freedom_gender', 'freedom_nationalism', 'freedom_religiosity',
        'socialism_family', 'socialism_ethnicity', 'socialism_gender', 'socialism_nationalism', 'socialism_religiosity', 
        'family_ethnicity', 'family_gender', 'family_nationalism', 'family_religiosity', 
        'ethnicity_gender', 'ethnicity_nationalism', 'ethnicity_religiosity', 
        'gender_nationalism', 'gender_religiosity', 
        'nationalism_religiosity']
        for i in self.correlation_names:
            exec(f"self.{i}_and_predictors = self.predictors_correlations[['authoritarian_socialism', 'culture_zone', 'hdi2010', 'v2x_libdem', '{i}']]")
            exec(f'self.{i}_and_predictors_clean = self.{i}_and_predictors.dropna()')
            exec(f"self.x = np.array(self.{i}_and_predictors_clean[['authoritarian_socialism', 'culture_zone', 'hdi2010', 'v2x_libdem']])")
            exec(f"self.y = np.array(self.{i}_and_predictors_clean[['{i}']])")
            exec(f'self.{i}_sklearn_model = LinearRegression()')
            exec(f'self.{i}_sklearn_model.fit(self.x, self.y)')
            exec(f'self.{i}_sklearn_score = self.{i}_sklearn_model.score(self.x, self.y)')
    
    def regression_statsmodels(self):
        self.correlation_names = ['freedom_socialism', 'freedom_family', 'freedom_ethnicity', 'freedom_gender', 'freedom_nationalism', 'freedom_religiosity',
        'socialism_family', 'socialism_ethnicity', 'socialism_gender', 'socialism_nationalism', 'socialism_religiosity', 
        'family_ethnicity', 'family_gender', 'family_nationalism', 'family_religiosity', 
        'ethnicity_gender', 'ethnicity_nationalism', 'ethnicity_religiosity', 
        'gender_nationalism', 'gender_religiosity', 
        'nationalism_religiosity']
        for i in self.correlation_names:
            exec(f"self.{i}_and_predictors = self.predictors_correlations[['authoritarian_socialism', 'culture_zone', 'hdi2010', 'v2x_libdem', '{i}']]")
            exec(f"self.{i}_and_predictors_clean = self.{i}_and_predictors.dropna()")
            exec(f"self.x = self.{i}_and_predictors_clean[['authoritarian_socialism', 'culture_zone', 'hdi2010', 'v2x_libdem']]")
            exec(f"self.y = self.{i}_and_predictors_clean['{i}']")
            exec(f"self.x = st.add_constant(self.x)")
            exec(f"self.{i}_statsmodels_model = st.OLS(self.y, self.x).fit()")

## Instantiating the class

In [64]:
CountryLevelDataAnalyzer = CountryLevelDataAnalysis()

## Caling the methods

In [65]:
CountryLevelDataAnalyzer.loading_country_level_predictors()

In [66]:
CountryLevelDataAnalyzer.loading_country_level_correlations()

In [67]:
CountryLevelDataAnalyzer.renaming_country_column()

In [68]:
CountryLevelDataAnalyzer.merging_data_frames()

In [69]:
CountryLevelDataAnalyzer.saving_merged_data()

In [70]:
CountryLevelDataAnalyzer.regression_sklearn()

In [71]:
CountryLevelDataAnalyzer.regression_statsmodels()

# The results

## The loading_country_level_predictors(), loading_country_level_correlations() and  renaming_country_column() methods

In [9]:
CountryLevelDataAnalyzer.predictors

iso_numeric iso_alpha_2 iso_alpha3 country_name  authoritarian_socialism  \
0              8          AL        ALB      Albania                      1.0   
1             12          DZ        DZA      Algeria                      0.5   
2             31          AZ        AZE   Azerbaijan                      1.0   
3             32          AR        ARG    Argentina                      0.0   
4             36          AU        AUS    Australia                      0.0   
..           ...         ...        ...          ...                      ...   
101          858          UY        URY      Uruguay                      0.0   
102          860          UZ        UZB   Uzbekistan                      1.0   
103          862          VE        VEN    Venezuela                      0.5   
104          887          YE        YEM        Yemen                      0.0   
105          894          ZM        ZMB       Zambia                      0.5   

     culture_zone  hdi2010  v2x_libdem  
0            0.00    0.677       0.341  
1            0.00    0.649       0.162  
2            0.00    0.622       0.084  
3            0.33    0.779       0.662  
4            1.00    0.896       0.849  
..            ...      ...         ...  
101          0.33    0.753       0.801  
102          0.00    0.607       0.035  
103          0.33    0.684       0.312  
104          0.00    0.450       0.138  
105          0.00    0.418       0.388  

[106 rows x 8 columns]

In [10]:
CountryLevelDataAnalyzer.correlations

iso_numeric  freedom_socialism  freedom_family  freedom_ethnicity  \
0              8              -0.05            0.07               0.06   
1             12              -0.15            0.04              -0.00   
2             20               0.07            0.32               0.06   
3             31              -0.01            0.05               0.03   
4             32              -0.04            0.28               0.18   
..           ...                ...             ...                ...   
113          862              -0.01            0.08               0.01   
114          887               0.10            0.21               0.01   
115          894               0.07            0.08               0.02   
116          909               0.01            0.43               0.19   
117          915                NaN             NaN                NaN   

     freedom_gender  freedom_nationalism  freedom_religiosity  \
0              0.11                -0.04                -0.07   
1              0.03                -0.11                -0.05   
2              0.20                -0.17                -0.10   
3              0.04                -0.06                -0.08   
4              0.22                -0.19                -0.14   
..              ...                  ...                  ...   
113            0.09                -0.02                -0.04   
114            0.20                -0.22                -0.29   
115            0.02                -0.25                -0.19   
116            0.21                  NaN                -0.09   
117             NaN                  NaN                  NaN   

     socialism_family  socialism_ethnicity  socialism_gender  ...  \
0               -0.11                -0.05              0.05  ...   
1                0.05                  NaN              0.02  ...   
2               -0.02                 0.10              0.00  ...   
3               -0.02                -0.09             -0.01  ...   
4                0.05                 0.02             -0.01  ...   
..                ...                  ...               ...  ...   
113             -0.03                 0.00             -0.00  ...   
114              0.12                 0.01              0.05  ...   
115              0.24                -0.03             -0.12  ...   
116             -0.04                -0.13              0.06  ...   
117              0.04                 0.02               NaN  ...   

     family_ethnicity  family_gender  family_nationalism  family_religiosity  \
0                0.12           0.01               -0.22               -0.17   
1                0.11           0.03               -0.09               -0.10   
2                0.04           0.26               -0.15               -0.40   
3                0.14           0.15               -0.04               -0.17   
4                0.12           0.24               -0.14               -0.32   
..                ...            ...                 ...                 ...   
113              0.10           0.07               -0.15               -0.18   
114             -0.03           0.05               -0.05               -0.19   
115             -0.07          -0.03               -0.00               -0.06   
116              0.11           0.32                0.02               -0.38   
117             -0.10            NaN                 NaN               -0.07   

     ethnicity_gender  ethnicity_nationalism  ethnicity_religiosity  \
0                0.22                  -0.02                  -0.05   
1                0.18                    NaN                  -0.01   
2                0.08                  -0.12                  -0.10   
3                0.02                   0.12                  -0.02   
4                0.20                  -0.11                  -0.08   
..                ...                    ...                    ...   
113              0.12                  -0.09    

## The merging_data_frames() method

In [11]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [12]:
CountryLevelDataAnalyzer.predictors_correlations

iso_numeric iso_alpha_2 iso_alpha3            country_name  \
0              8          AL        ALB                 Albania   
1             12          DZ        DZA                 Algeria   
2             31          AZ        AZE              Azerbaijan   
3             32          AR        ARG               Argentina   
4             36          AU        AUS               Australia   
5             40          AT        AUT                 Austria   
6             50          BD        BGD              Bangladesh   
7             51          AM        ARM                 Armenia   
8             56          BE        BEL                 Belgium   
9             68          BO        BOL                 Bolivia   
10            70          BA        BIH  Bosnia and Herzegovina   
11            76          BR        BRA                  Brazil   
12           100          BR        BGR                Bulgaria   
13           104          MM        MMR                 Myanmar   
14           112          BY        BLR                 Belarus   
15           124          CA        CAN                  Canada   
16           152          CL        CHL                   Chile   
17           156          CN        CHN                   China   
18           170          CO        COL                Colombia   
19           191          HR        HRV                 Croatia   
20           196          CY        CYP                  Cyprus   
21           203          CZ        CZE          Czech Republic   
22           208          DK        DNK                 Denmark   
23           214          DO        DOM      Dominican Republic   
24           218          EC        ECU                 Ecuador   
25           222          SV        SLV             El Salvador   
26           231          ET        ETH                Ethiopia   
27           233          EE        EST                 Estonia   
28           246          FI        FIN                 Finland   
29           250          FR        FRA                  France   
30           268          GE        GEO                 Georgia   
31           276          DE        DEU                 Germany   
32           288          GH        GHA                   Ghana   
33           300          GR        GRC                  Greece   
34           320          GT        GTM               Guatemala   
35           332          HT        HTI                   Haiti   
36           344          HK        HKG               Hong Kong   
37           348          HU        HUN                 Hungary   
38           352          IS        ISL                 Iceland   
39           356          IN        IND                   India   
40           360          ID        IDN               Indonesia   
41           364          IR        IRN                    Iran   
42           368          IQ        IRQ                    Iraq   
43           372          IE        IRL                 Ireland   
44           376          IL        ISR                  Israel   
45           380          IT        ITA                   Italy   
46           392          JP        JPN                   Japan   
47           398          KZ        KAZ              Kazakhstan   
48           400          JO        JOR                  Jordan   
49           404          KE        KEN                   Kenya   
50           410          KR        KOR             South Korea   
51           414          KW        KWT                  Kuwait   
52           417          KG        KGZ              Kyrgyzstan   
53           428          LV        LVA                  Latvia   
54           434          LY        LBY                   Libya   
55           440          LT        LTU               Lithuania   
56           442          LU        LUX              Luxembourg   
57           458          MY        MYS                Malaysia   
58           462          MV        MDV             

## The saving_merged_data() method

In [13]:
country_data = pd.read_csv('./country_level_processed_data/predictors_correlations.csv')

In [14]:
country_data

Unnamed: 0  iso_numeric iso_alpha_2 iso_alpha3            country_name  \
0             0            8          AL        ALB                 Albania   
1             1           12          DZ        DZA                 Algeria   
2             2           31          AZ        AZE              Azerbaijan   
3             3           32          AR        ARG               Argentina   
4             4           36          AU        AUS               Australia   
5             5           40          AT        AUT                 Austria   
6             6           50          BD        BGD              Bangladesh   
7             7           51          AM        ARM                 Armenia   
8             8           56          BE        BEL                 Belgium   
9             9           68          BO        BOL                 Bolivia   
10           10           70          BA        BIH  Bosnia and Herzegovina   
11           11           76          BR        BRA                  Brazil   
12           12          100          BR        BGR                Bulgaria   
13           13          104          MM        MMR                 Myanmar   
14           14          112          BY        BLR                 Belarus   
15           15          124          CA        CAN                  Canada   
16           16          152          CL        CHL                   Chile   
17           17          156          CN        CHN                   China   
18           18          170          CO        COL                Colombia   
19           19          191          HR        HRV                 Croatia   
20           20          196          CY        CYP                  Cyprus   
21           21          203          CZ        CZE          Czech Republic   
22           22          208          DK        DNK                 Denmark   
23           23          214          DO        DOM      Dominican Republic   
24           24          218          EC        ECU                 Ecuador   
25           25          222          SV        SLV             El Salvador   
26           26          231          ET        ETH                Ethiopia   
27           27          233          EE        EST                 Estonia   
28           28          246          FI        FIN                 Finland   
29           29          250          FR        FRA                  France   
30           30          268          GE        GEO                 Georgia   
31           31          276          DE        DEU                 Germany   
32           32          288          GH        GHA                   Ghana   
33           33          300          GR        GRC                  Greece   
34           34          320          GT        GTM               Guatemala   
35           35          332          HT        HTI                   Haiti   
36           36          344          HK        HKG               Hong Kong   
37           37          348          HU        HUN                 Hungary   
38           38          352          IS        ISL                 Iceland   
39           39          356          IN        IND                   India   
40           40          360          ID        IDN               Indonesia   
41           41          364          IR        IRN                    Iran   
42           42          368          IQ        IRQ                    Iraq   
43           43          372          IE        IRL                 Ireland   
44           44          376          IL        ISR                  Israel   
45           45          380          IT        ITA                   Italy   
46           46          392          JP        JPN                   Japan   
47           47          398          KZ        KAZ              Kazakhstan   
48           48          400          JO        JOR                  Jordan   
49           49          404          KE        KEN    

## The regression_models() method

In [35]:
for i in CountryLevelDataAnalyzer.correlation_names:
    exec(f"print(['{i}', round(CountryLevelDataAnalyzer.{i}_score, 2)])")

['freedom_socialism', 0.34]
['freedom_family', 0.63]
['freedom_ethnicity', 0.5]
['freedom_gender', 0.5]
['freedom_nationalism', 0.18]
['freedom_religiosity', 0.14]
['socialism_family', 0.2]
['socialism_ethnicity', 0.18]
['socialism_gender', 0.05]
['socialism_nationalism', 0.24]
['socialism_religiosity', 0.19]
['family_ethnicity', 0.61]
['family_gender', 0.74]
['family_nationalism', 0.1]
['family_religiosity', 0.73]
['ethnicity_gender', 0.3]
['ethnicity_nationalism', 0.12]
['ethnicity_religiosity', 0.05]
['gender_nationalism', 0.08]
['gender_religiosity', 0.27]
['nationalism_religiosity', 0.24]


In [45]:
CountryLevelDataAnalyzer.family_gender_model.coef_

array([[0.03063081, 0.15387163, 0.41728125, 0.10958928]])

In [46]:
CountryLevelDataAnalyzer.family_religiosity_model.coef_

array([[-0.03009326, -0.09652887, -0.33036605, -0.18296926]])

In [47]:
CountryLevelDataAnalyzer.family_ethnicity_model.coef_

array([[0.00867261, 0.0170214 , 0.45844321, 0.0344159 ]])

In [48]:
CountryLevelDataAnalyzer.freedom_family_model.coef_

array([[0.01410771, 0.10557649, 0.30708496, 0.11618442]])

In [49]:
CountryLevelDataAnalyzer.freedom_gender_model.coef_

array([[0.00568494, 0.06610076, 0.23933779, 0.05850531]])

In [50]:
CountryLevelDataAnalyzer.freedom_ethnicity_model.coef_

array([[0.0075514 , 0.11248593, 0.19784395, 0.07069894]])

In [51]:
CountryLevelDataAnalyzer.freedom_socialism_model.coef_

array([[-0.01653919,  0.11006107, -0.14960354,  0.09376453]])

In [52]:
CountryLevelDataAnalyzer.ethnicity_gender_model.coef_

array([[-0.00617359,  0.09464071,  0.14103413,  0.02082337]])

In [53]:
CountryLevelDataAnalyzer.gender_religiosity_model.coef_

array([[-0.01966049, -0.0361413 , -0.31178592,  0.03831286]])

In [55]:
CountryLevelDataAnalyzer.socialism_nationalism_model.coef_

array([[-0.02491997, -0.01083081,  0.00931982, -0.10930467]])

In [56]:
CountryLevelDataAnalyzer.nationalism_religiosity_model.coef_

array([[-0.07994186, -0.07590958,  0.1269531 , -0.07524136]])

In [57]:
CountryLevelDataAnalyzer.socialism_family_model.coef_

array([[-0.04494396,  0.06408819, -0.12649499, -0.02573447]])

In [58]:
CountryLevelDataAnalyzer.socialism_religiosity_model.coef_

array([[ 0.03479515, -0.03354578,  0.08057008,  0.05167406]])

In [59]:
CountryLevelDataAnalyzer.freedom_nationalism_model.coef_

array([[ 0.01294754, -0.07451907, -0.09116321,  0.00937008]])

In [60]:
CountryLevelDataAnalyzer.socialism_ethnicity_model.coef_

array([[-0.03571859,  0.0272408 ,  0.09470936, -0.05036362]])

In [61]:
CountryLevelDataAnalyzer.freedom_religiosity_model.coef_

array([[ 0.03234512,  0.02209559, -0.05140664, -0.06053201]])

In [62]:
CountryLevelDataAnalyzer.ethnicity_nationalism_model.coef_

array([[ 0.01547906, -0.03818682, -0.03327712, -0.01726407]])

In [63]:
CountryLevelDataAnalyzer.family_nationalism_model.coef_

array([[-0.01937848, -0.0050575 , -0.14739706,  0.00233549]])

In [64]:
CountryLevelDataAnalyzer.gender_nationalism_model.coef_

array([[ 0.02492735, -0.03318999, -0.07692823,  0.02110023]])

In [65]:
CountryLevelDataAnalyzer.socialism_gender_model.coef_

array([[-0.01082418,  0.04204323, -0.00263447, -0.01744316]])

In [66]:
CountryLevelDataAnalyzer.ethnicity_religiosity_model.coef_

array([[ 0.00739048,  0.05127888,  0.00025654, -0.02367227]])

## Statsmodels regressions

In [74]:
CountryLevelDataAnalyzer.family_gender_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:          family_gender   R-squared:                       0.739
Model:                            OLS   Adj. R-squared:                  0.728
Method:                 Least Squares   F-statistic:                     66.55
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           1.36e-26
Time:                        15:12:54   Log-Likelihood:                 121.27
No. Observations:                  99   AIC:                            -232.5
Df Residuals:                      94   BIC:                            -219.6
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.2175      0.038     -5.701      0.000      -0.293      -0.142
authoritarian_socialism     0.0306      0.018      1.702      0.092      -0.005       0.066
culture_zone                0.1539      0.034      4.520      0.000       0.086       0.221
hdi2010                     0.4173      0.066      6.282      0.000       0.285       0.549
v2x_libdem                  0.1096      0.038      2.916      0.004       0.035       0.184
==============================================================================
Omnibus:                        1.748   Durbin-Watson:                   2.260
Prob(Omnibus):                  0.417   Jarque-Bera (JB):                1.179
Skew:                           0.186   Prob(JB):                        0.555
Kurtosis:                       3.383   Cond. No.                         14.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [75]:
CountryLevelDataAnalyzer.family_religiosity_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     family_religiosity   R-squared:                       0.732
Model:                            OLS   Adj. R-squared:                  0.721
Method:                 Least Squares   F-statistic:                     66.19
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           6.87e-27
Time:                        15:33:47   Log-Likelihood:                 128.06
No. Observations:                 102   AIC:                            -246.1
Df Residuals:                      97   BIC:                            -233.0
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.1306      0.037      3.509      0.001       0.057       0.204
authoritarian_socialism    -0.0301      0.018     -1.713      0.090      -0.065       0.005
culture_zone               -0.0965      0.032     -3.011      0.003      -0.160      -0.033
hdi2010                    -0.3304      0.066     -4.995      0.000      -0.462      -0.199
v2x_libdem                 -0.1830      0.037     -4.920      0.000      -0.257      -0.109
==============================================================================
Omnibus:                        2.087   Durbin-Watson:                   2.090
Prob(Omnibus):                  0.352   Jarque-Bera (JB):                1.566
Skew:                           0.282   Prob(JB):                        0.457
Kurtosis:                       3.227   Cond. No.                         15.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [76]:
CountryLevelDataAnalyzer.family_ethnicity_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:       family_ethnicity   R-squared:                       0.606
Model:                            OLS   Adj. R-squared:                  0.590
Method:                 Least Squares   F-statistic:                     37.34
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           7.08e-19
Time:                        15:36:43   Log-Likelihood:                 134.54
No. Observations:                 102   AIC:                            -259.1
Df Residuals:                      97   BIC:                            -246.0
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.2542      0.035     -7.313      0.000      -0.323      -0.185
authoritarian_socialism     0.0087      0.016      0.530      0.597      -0.024       0.041
culture_zone                0.0170      0.030      0.567      0.572      -0.043       0.077
hdi2010                     0.4584      0.060      7.600      0.000       0.339       0.578
v2x_libdem                  0.0344      0.034      1.006      0.317      -0.033       0.102
==============================================================================
Omnibus:                        1.748   Durbin-Watson:                   1.923
Prob(Omnibus):                  0.417   Jarque-Bera (JB):                1.265
Skew:                          -0.063   Prob(JB):                        0.531
Kurtosis:                       3.531   Cond. No.                         14.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [77]:
CountryLevelDataAnalyzer.freedom_family_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:         freedom_family   R-squared:                       0.633
Model:                            OLS   Adj. R-squared:                  0.616
Method:                 Least Squares   F-statistic:                     39.17
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           4.88e-19
Time:                        15:37:59   Log-Likelihood:                 114.79
No. Observations:                  96   AIC:                            -219.6
Df Residuals:                      91   BIC:                            -206.7
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.1340      0.040     -3.363      0.001      -0.213      -0.055
authoritarian_socialism     0.0141      0.019      0.746      0.458      -0.023       0.052
culture_zone                0.1056      0.035      2.988      0.004       0.035       0.176
hdi2010                     0.3071      0.072      4.249      0.000       0.164       0.451
v2x_libdem                  0.1162      0.041      2.842      0.006       0.035       0.197
==============================================================================
Omnibus:                        7.916   Durbin-Watson:                   1.680
Prob(Omnibus):                  0.019   Jarque-Bera (JB):               15.263
Skew:                          -0.129   Prob(JB):                     0.000485
Kurtosis:                       4.936   Cond. No.                         15.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [78]:
CountryLevelDataAnalyzer.freedom_gender_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:         freedom_gender   R-squared:                       0.497
Model:                            OLS   Adj. R-squared:                  0.475
Method:                 Least Squares   F-statistic:                     22.96
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           3.23e-13
Time:                        15:39:42   Log-Likelihood:                 130.44
No. Observations:                  98   AIC:                            -250.9
Df Residuals:                      93   BIC:                            -238.0
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.0488      0.035     -1.405      0.163      -0.118       0.020
authoritarian_socialism     0.0057      0.016      0.347      0.729      -0.027       0.038
culture_zone                0.0661      0.031      2.149      0.034       0.005       0.127
hdi2010                     0.2393      0.063      3.803      0.000       0.114       0.364
v2x_libdem                  0.0585      0.035      1.662      0.100      -0.011       0.128
==============================================================================
Omnibus:                       16.685   Durbin-Watson:                   2.074
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               21.063
Skew:                           0.866   Prob(JB):                     2.67e-05
Kurtosis:                       4.468   Cond. No.                         15.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [81]:
CountryLevelDataAnalyzer.freedom_ethnicity_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:      freedom_ethnicity   R-squared:                       0.497
Model:                            OLS   Adj. R-squared:                  0.475
Method:                 Least Squares   F-statistic:                     22.50
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           6.10e-13
Time:                        15:50:31   Log-Likelihood:                 114.80
No. Observations:                  96   AIC:                            -219.6
Df Residuals:                      91   BIC:                            -206.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.1131      0.040     -2.833      0.006      -0.192      -0.034
authoritarian_socialism     0.0076      0.019      0.402      0.689      -0.030       0.045
culture_zone                0.1125      0.035      3.185      0.002       0.042       0.183
hdi2010                     0.1978      0.072      2.737      0.007       0.054       0.341
v2x_libdem                  0.0707      0.041      1.738      0.086      -0.010       0.152
==============================================================================
Omnibus:                        3.387   Durbin-Watson:                   2.457
Prob(Omnibus):                  0.184   Jarque-Bera (JB):                2.730
Skew:                           0.317   Prob(JB):                        0.255
Kurtosis:                       3.529   Cond. No.                         15.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [82]:
CountryLevelDataAnalyzer.freedom_socialism_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:      freedom_socialism   R-squared:                       0.340
Model:                            OLS   Adj. R-squared:                  0.312
Method:                 Least Squares   F-statistic:                     11.98
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           6.79e-08
Time:                        15:50:37   Log-Likelihood:                 133.29
No. Observations:                  98   AIC:                            -256.6
Df Residuals:                      93   BIC:                            -243.7
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.0266      0.034      0.788      0.432      -0.040       0.094
authoritarian_socialism    -0.0165      0.016     -1.040      0.301      -0.048       0.015
culture_zone                0.1101      0.030      3.683      0.000       0.051       0.169
hdi2010                    -0.1496      0.061     -2.447      0.016      -0.271      -0.028
v2x_libdem                  0.0938      0.034      2.743      0.007       0.026       0.162
==============================================================================
Omnibus:                        0.043   Durbin-Watson:                   1.626
Prob(Omnibus):                  0.979   Jarque-Bera (JB):                0.132
Skew:                          -0.048   Prob(JB):                        0.936
Kurtosis:                       2.848   Cond. No.                         15.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [83]:
CountryLevelDataAnalyzer.ethnicity_gender_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:       ethnicity_gender   R-squared:                       0.304
Model:                            OLS   Adj. R-squared:                  0.274
Method:                 Least Squares   F-statistic:                     10.36
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           5.24e-07
Time:                        15:52:46   Log-Likelihood:                 116.54
No. Observations:                 100   AIC:                            -223.1
Df Residuals:                      95   BIC:                            -210.0
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.0463      0.040      1.146      0.255      -0.034       0.127
authoritarian_socialism    -0.0062      0.019     -0.329      0.743      -0.043       0.031
culture_zone                0.0946      0.036      2.638      0.010       0.023       0.166
hdi2010                     0.1410      0.069      2.030      0.045       0.003       0.279
v2x_libdem                  0.0208      0.040      0.527      0.599      -0.058       0.099
==============================================================================
Omnibus:                        0.980   Durbin-Watson:                   2.196
Prob(Omnibus):                  0.613   Jarque-Bera (JB):                1.015
Skew:                          -0.228   Prob(JB):                        0.602
Kurtosis:                       2.813   Cond. No.                         14.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [84]:
CountryLevelDataAnalyzer.gender_religiosity_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     gender_religiosity   R-squared:                       0.269
Model:                            OLS   Adj. R-squared:                  0.238
Method:                 Least Squares   F-statistic:                     8.663
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           5.37e-06
Time:                        15:54:15   Log-Likelihood:                 112.49
No. Observations:                  99   AIC:                            -215.0
Df Residuals:                      94   BIC:                            -202.0
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.1418      0.042      3.375      0.001       0.058       0.225
authoritarian_socialism    -0.0197      0.020     -0.999      0.320      -0.059       0.019
culture_zone               -0.0361      0.037     -0.970      0.335      -0.110       0.038
hdi2010                    -0.3118      0.075     -4.171      0.000      -0.460      -0.163
v2x_libdem                  0.0383      0.042      0.919      0.361      -0.044       0.121
==============================================================================
Omnibus:                       11.933   Durbin-Watson:                   2.568
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               18.054
Skew:                          -0.530   Prob(JB):                     0.000120
Kurtosis:                       4.803   Cond. No.                         15.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [85]:
CountryLevelDataAnalyzer.socialism_nationalism_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results                             
=================================================================================
Dep. Variable:     socialism_nationalism   R-squared:                       0.236
Model:                               OLS   Adj. R-squared:                  0.204
Method:                    Least Squares   F-statistic:                     7.553
Date:                   Sun, 25 Jun 2023   Prob (F-statistic):           2.40e-05
Time:                           15:55:43   Log-Likelihood:                 149.89
No. Observations:                    103   AIC:                            -289.8
Df Residuals:                         98   BIC:                            -276.6
Df Model:                              4                                         
Covariance Type:               nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.0076      0.030      0.251      0.802      -0.052       0.067
authoritarian_socialism    -0.0249      0.014     -1.766      0.081      -0.053       0.003
culture_zone               -0.0108      0.026     -0.417      0.677      -0.062       0.041
hdi2010                     0.0093      0.053      0.177      0.860      -0.095       0.114
v2x_libdem                 -0.1093      0.030     -3.636      0.000      -0.169      -0.050
==============================================================================
Omnibus:                        7.493   Durbin-Watson:                   1.974
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                7.726
Skew:                          -0.476   Prob(JB):                       0.0210
Kurtosis:                       3.945   Cond. No.                         15.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [86]:
CountryLevelDataAnalyzer.nationalism_religiosity_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                               OLS Regression Results                              
===================================================================================
Dep. Variable:     nationalism_religiosity   R-squared:                       0.240
Model:                                 OLS   Adj. R-squared:                  0.208
Method:                      Least Squares   F-statistic:                     7.649
Date:                     Sun, 25 Jun 2023   Prob (F-statistic):           2.12e-05
Time:                             15:57:10   Log-Likelihood:                 135.40
No. Observations:                      102   AIC:                            -260.8
Df Residuals:                           97   BIC:                            -247.7
Df Model:                                4                                         
Covariance Type:                 nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.0617      0.035      1.775      0.079      -0.007       0.131
authoritarian_socialism    -0.0799      0.016     -4.882      0.000      -0.112      -0.047
culture_zone               -0.0759      0.030     -2.544      0.013      -0.135      -0.017
hdi2010                     0.1270      0.063      2.017      0.046       0.002       0.252
v2x_libdem                 -0.0752      0.035     -2.135      0.035      -0.145      -0.005
==============================================================================
Omnibus:                        0.555   Durbin-Watson:                   2.274
Prob(Omnibus):                  0.758   Jarque-Bera (JB):                0.692
Skew:                           0.088   Prob(JB):                        0.707
Kurtosis:                       2.637   Cond. No.                         15.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [87]:
CountryLevelDataAnalyzer.socialism_family_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:       socialism_family   R-squared:                       0.197
Model:                            OLS   Adj. R-squared:                  0.163
Method:                 Least Squares   F-statistic:                     5.874
Date:                Sun, 25 Jun 2023   Prob (F-statistic):           0.000285
Time:                        15:59:09   Log-Likelihood:                 134.68
No. Observations:                 101   AIC:                            -259.4
Df Residuals:                      96   BIC:                            -246.3
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.0925      0.034      2.699      0.008       0.024       0.160
authoritarian_socialism    -0.0449      0.016     -2.768      0.007      -0.077      -0.013
culture_zone                0.0641      0.030      2.166      0.033       0.005       0.123
hdi2010                    -0.1265      0.061     -2.085      0.040      -0.247      -0.006
v2x_libdem                 -0.0257      0.035     -0.743      0.459      -0.094       0.043
==============================================================================
Omnibus:                       11.479   Durbin-Watson:                   1.546
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               18.014
Skew:                           0.485   Prob(JB):                     0.000123
Kurtosis:                       4.827   Cond. No.                         15.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [88]:
CountryLevelDataAnalyzer.socialism_religiosity_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results                             
=================================================================================
Dep. Variable:     socialism_religiosity   R-squared:                       0.186
Model:                               OLS   Adj. R-squared:                  0.153
Method:                    Least Squares   F-statistic:                     5.546
Date:                   Sun, 25 Jun 2023   Prob (F-statistic):           0.000460
Time:                           16:01:21   Log-Likelihood:                 156.73
No. Observations:                    102   AIC:                            -303.5
Df Residuals:                         97   BIC:                            -290.3
Df Model:                              4                                         
Covariance Type:               nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.0787      0.028     -2.790      0.006      -0.135      -0.023
authoritarian_socialism     0.0348      0.013      2.620      0.010       0.008       0.061
culture_zone               -0.0335      0.024     -1.386      0.169      -0.082       0.014
hdi2010                     0.0806      0.051      1.578      0.118      -0.021       0.182
v2x_libdem                  0.0517      0.029      1.807      0.074      -0.005       0.108
==============================================================================
Omnibus:                        2.644   Durbin-Watson:                   1.676
Prob(Omnibus):                  0.267   Jarque-Bera (JB):                2.389
Skew:                          -0.094   Prob(JB):                        0.303
Kurtosis:                       3.726   Cond. No.                         15.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [89]:
CountryLevelDataAnalyzer.freedom_nationalism_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results                            
===============================================================================
Dep. Variable:     freedom_nationalism   R-squared:                       0.185
Model:                             OLS   Adj. R-squared:                  0.150
Method:                  Least Squares   F-statistic:                     5.275
Date:                 Sun, 25 Jun 2023   Prob (F-statistic):           0.000713
Time:                         16:24:44   Log-Likelihood:                 121.19
No. Observations:                   98   AIC:                            -232.4
Df Residuals:                       93   BIC:                            -219.5
Df Model:                            4                                         
Covariance Type:             nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.0238      0.038     -0.622      0.535      -0.100       0.052
authoritarian_socialism     0.0129      0.018      0.720      0.474      -0.023       0.049
culture_zone               -0.0745      0.034     -2.204      0.030      -0.142      -0.007
hdi2010                    -0.0912      0.069     -1.318      0.191      -0.229       0.046
v2x_libdem                  0.0094      0.039      0.242      0.809      -0.067       0.086
==============================================================================
Omnibus:                        1.968   Durbin-Watson:                   2.134
Prob(Omnibus):                  0.374   Jarque-Bera (JB):                1.396
Skew:                          -0.250   Prob(JB):                        0.498
Kurtosis:                       3.304   Cond. No.                         15.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [90]:
CountryLevelDataAnalyzer.socialism_ethnicity_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results                            
===============================================================================
Dep. Variable:     socialism_ethnicity   R-squared:                       0.181
Model:                             OLS   Adj. R-squared:                  0.147
Method:                  Least Squares   F-statistic:                     5.361
Date:                 Sun, 25 Jun 2023   Prob (F-statistic):           0.000607
Time:                         16:25:54   Log-Likelihood:                 160.75
No. Observations:                  102   AIC:                            -311.5
Df Residuals:                       97   BIC:                            -298.4
Df Model:                            4                                         
Covariance Type:             nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.0475      0.027     -1.770      0.080      -0.101       0.006
authoritarian_socialism    -0.0357      0.013     -2.852      0.005      -0.061      -0.011
culture_zone                0.0272      0.023      1.184      0.239      -0.018       0.073
hdi2010                     0.0947      0.047      2.021      0.046       0.002       0.188
v2x_libdem                 -0.0504      0.027     -1.875      0.064      -0.104       0.003
==============================================================================
Omnibus:                        3.723   Durbin-Watson:                   1.752
Prob(Omnibus):                  0.155   Jarque-Bera (JB):                4.146
Skew:                           0.099   Prob(JB):                        0.126
Kurtosis:                       3.968   Cond. No.                         15.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [91]:
CountryLevelDataAnalyzer.freedom_religiosity_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results                            
===============================================================================
Dep. Variable:     freedom_religiosity   R-squared:                       0.136
Model:                             OLS   Adj. R-squared:                  0.099
Method:                  Least Squares   F-statistic:                     3.662
Date:                 Sun, 25 Jun 2023   Prob (F-statistic):            0.00815
Time:                         16:27:07   Log-Likelihood:                 132.28
No. Observations:                   98   AIC:                            -254.6
Df Residuals:                       93   BIC:                            -241.6
Df Model:                            4                                         
Covariance Type:             nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.0816      0.034     -2.391      0.019      -0.149      -0.014
authoritarian_socialism     0.0323      0.016      2.013      0.047       0.000       0.064
culture_zone                0.0221      0.030      0.732      0.466      -0.038       0.082
hdi2010                    -0.0514      0.062     -0.832      0.407      -0.174       0.071
v2x_libdem                 -0.0605      0.035     -1.753      0.083      -0.129       0.008
==============================================================================
Omnibus:                        1.923   Durbin-Watson:                   1.838
Prob(Omnibus):                  0.382   Jarque-Bera (JB):                1.349
Skew:                          -0.240   Prob(JB):                        0.509
Kurtosis:                       3.316   Cond. No.                         15.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [92]:
CountryLevelDataAnalyzer.ethnicity_nationalism_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results                             
=================================================================================
Dep. Variable:     ethnicity_nationalism   R-squared:                       0.115
Model:                               OLS   Adj. R-squared:                  0.079
Method:                    Least Squares   F-statistic:                     3.161
Date:                   Sun, 25 Jun 2023   Prob (F-statistic):             0.0173
Time:                           16:31:28   Log-Likelihood:                 136.68
No. Observations:                    102   AIC:                            -263.4
Df Residuals:                         97   BIC:                            -250.2
Df Model:                              4                                         
Covariance Type:               nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.0039      0.034      0.115      0.908      -0.063       0.071
authoritarian_socialism     0.0155      0.016      0.976      0.332      -0.016       0.047
culture_zone               -0.0382      0.029     -1.310      0.193      -0.096       0.020
hdi2010                    -0.0333      0.059     -0.561      0.576      -0.151       0.085
v2x_libdem                 -0.0173      0.034     -0.508      0.613      -0.085       0.050
==============================================================================
Omnibus:                        0.420   Durbin-Watson:                   1.800
Prob(Omnibus):                  0.811   Jarque-Bera (JB):                0.417
Skew:                          -0.148   Prob(JB):                        0.812
Kurtosis:                       2.895   Cond. No.                         15.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [94]:
CountryLevelDataAnalyzer.family_nationalism_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     family_nationalism   R-squared:                       0.099
Model:                            OLS   Adj. R-squared:                  0.062
Method:                 Least Squares   F-statistic:                     2.663
Date:                Sun, 25 Jun 2023   Prob (F-statistic):             0.0370
Time:                        16:34:52   Log-Likelihood:                 124.69
No. Observations:                 102   AIC:                            -239.4
Df Residuals:                      97   BIC:                            -226.3
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                       0.0204      0.038      0.537      0.593      -0.055       0.096
authoritarian_socialism    -0.0194      0.018     -1.081      0.283      -0.055       0.016
culture_zone               -0.0051      0.032     -0.157      0.876      -0.069       0.059
hdi2010                    -0.1474      0.067     -2.192      0.031      -0.281      -0.014
v2x_libdem                  0.0023      0.039      0.061      0.952      -0.074       0.079
==============================================================================
Omnibus:                        0.709   Durbin-Watson:                   1.913
Prob(Omnibus):                  0.701   Jarque-Bera (JB):                0.306
Skew:                           0.070   Prob(JB):                        0.858
Kurtosis:                       3.228   Cond. No.                         15.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [95]:
CountryLevelDataAnalyzer.gender_nationalism_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     gender_nationalism   R-squared:                       0.076
Model:                            OLS   Adj. R-squared:                  0.037
Method:                 Least Squares   F-statistic:                     1.949
Date:                Sun, 25 Jun 2023   Prob (F-statistic):              0.109
Time:                        16:37:17   Log-Likelihood:                 116.98
No. Observations:                 100   AIC:                            -224.0
Df Residuals:                      95   BIC:                            -210.9
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.0059      0.040     -0.148      0.883      -0.086       0.074
authoritarian_socialism     0.0249      0.019      1.325      0.188      -0.012       0.062
culture_zone               -0.0332      0.036     -0.930      0.355      -0.104       0.038
hdi2010                    -0.0769      0.070     -1.094      0.277      -0.217       0.063
v2x_libdem                  0.0211      0.040      0.527      0.600      -0.058       0.101
==============================================================================
Omnibus:                        2.040   Durbin-Watson:                   2.129
Prob(Omnibus):                  0.361   Jarque-Bera (JB):                1.458
Skew:                          -0.196   Prob(JB):                        0.482
Kurtosis:                       3.443   Cond. No.                         14.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [96]:
CountryLevelDataAnalyzer.socialism_gender_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:       socialism_gender   R-squared:                       0.053
Model:                            OLS   Adj. R-squared:                  0.013
Method:                 Least Squares   F-statistic:                     1.322
Date:                Sun, 25 Jun 2023   Prob (F-statistic):              0.267
Time:                        16:38:09   Log-Likelihood:                 146.91
No. Observations:                 100   AIC:                            -283.8
Df Residuals:                      95   BIC:                            -270.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.0171      0.030     -0.573      0.568      -0.076       0.042
authoritarian_socialism    -0.0108      0.014     -0.776      0.440      -0.039       0.017
culture_zone                0.0420      0.026      1.589      0.115      -0.010       0.095
hdi2010                    -0.0026      0.052     -0.051      0.960      -0.106       0.101
v2x_libdem                 -0.0174      0.030     -0.587      0.558      -0.076       0.042
==============================================================================
Omnibus:                        7.441   Durbin-Watson:                   2.317
Prob(Omnibus):                  0.024   Jarque-Bera (JB):                6.944
Skew:                           0.593   Prob(JB):                       0.0311
Kurtosis:                       3.512   Cond. No.                         14.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [97]:
CountryLevelDataAnalyzer.ethnicity_religiosity_statsmodels_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results                             
=================================================================================
Dep. Variable:     ethnicity_religiosity   R-squared:                       0.054
Model:                               OLS   Adj. R-squared:                  0.014
Method:                    Least Squares   F-statistic:                     1.362
Date:                   Sun, 25 Jun 2023   Prob (F-statistic):              0.253
Time:                           16:38:55   Log-Likelihood:                 155.49
No. Observations:                    101   AIC:                            -301.0
Df Residuals:                         96   BIC:                            -287.9
Df Model:                              4                                         
Covariance Type:               nonrobust                                         
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -0.0357      0.028     -1.269      0.208      -0.091       0.020
authoritarian_socialism     0.0074      0.013      0.563      0.575      -0.019       0.033
culture_zone                0.0513      0.024      2.126      0.036       0.003       0.099
hdi2010                     0.0003      0.050      0.005      0.996      -0.099       0.099
v2x_libdem                 -0.0237      0.028     -0.842      0.402      -0.079       0.032
==============================================================================
Omnibus:                        4.665   Durbin-Watson:                   2.169
Prob(Omnibus):                  0.097   Jarque-Bera (JB):                3.992
Skew:                          -0.442   Prob(JB):                        0.136
Kurtosis:                       3.410   Cond. No.                         15.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""