In [4]:
import numpy as np
import pandas as pd

# The class, the object, the data and the methods

## Defining the class

In [5]:
class IndividualLevelIndexBuilding:
    dataset_names = ['freedom_data', 'socialism_data', 'family_data', 'ethnicity_data', 'gender_data', 'nationalism_data', 'religiosity_data']
    def loading_each_dataset(self):
        for x in self.dataset_names:
            exec(f"self.{x} = pd.read_csv('./individual_level_extracted_data/{x}.csv')")
        self.demographics_data = pd.read_csv('./individual_level_extracted_data/demographics_data.csv')
        
    def recoding_demographics(self):
        self.demographics_data = self.demographics_data.assign(country = self.demographics_data.S003)
        self.demographics_data = self.demographics_data.assign(gender = self.demographics_data.X001.map({1: 0, 2: 1, -2: None, -4: None, -5: None}))
        self.demographics_data = self.demographics_data.assign(education = self.demographics_data.X025.map({0: 0, 1: 0, 2: 0, 3: 0.5, 4: 0.5, 5: 0.5, 6: 1, 7: 1, 8: 1, -1: 0, -2: None, -4: None, -5: None}))
        self.demographics_data = self.demographics_data.assign(social_class = self.demographics_data.X045.map({1: 1, 2: 0.75, 3: 0.5, 4: 0.25, 5: 0, -1: 0.5, -2: None, -4: None, -5: None}))
        self.demographics_data = self.demographics_data.assign(income = self.demographics_data.X047_IVS.map({1: 0, 2: 0, 3: 0.25, 4: 0.25, 5: 0.5, 6: 0.5, 7: 0.75, 8: 0.75, 9: 1, 10: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.demographics_data = self.demographics_data.assign(urban = self.demographics_data.X049.map({1: 0, 2: 0, 3: 0.25, 4: 0.25, 5: 0.25, 6: 0.5, 7: 0.75, 8: 1, -4: None, -5: None}))
        
    def recoding_age(self):
        self.age_numbers = []
        self.string_list = []
        self.x = range(1, 104)
        for n in self.x:
            self.age_numbers.append(n)
        for a in self.age_numbers:
            self.string_list.append(f'{a}: {a}, ')
        self.string_list.append('108: 108, ')
        for b in [-1, -2, -4, -5]:
            if b > -5:
                self.string_list.append(f'{b}: None, ')
            else:
                self.string_list.append(f'{b}: None')
        self.string_list = ['{'] + self.string_list + ['}']
        self.age_string = ''.join(self.string_list)
        exec(f'self.demographics_data = self.demographics_data.assign(age = self.demographics_data.X003.map({self.age_string}))')
        
#child independence, child imagination, child faith, child obedience, future authority, aims of country, aims of respondent, strong leader, army rule, democratic system
    def recoding_freedom(self):
        self.freedom_data = self.freedom_data.assign(child_independence = self.freedom_data.A029.map({0: 0, 1: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.freedom_data = self.freedom_data.assign(child_imagination = self.freedom_data.A034.map({0: 0, 1: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.freedom_data = self.freedom_data.assign(child_obedience = self.freedom_data.A042.map({0: 1, 1: 0, -1: 0.5, -2: None, -4: None, -5: None}))
        self.freedom_data = self.freedom_data.assign(respect_authority = self.freedom_data.E018.map({1: 0, 2: 0.5, 3: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.freedom_data = self.freedom_data.assign(aim_of_country = self.freedom_data.E001.map({1: 0, 2: 0, 3: 1, 4: 0, -1: 0.5, -2: None, -4: None, -5: None}))
        self.freedom_data = self.freedom_data.assign(aim_of_respondent = self.freedom_data.E003.map({1: 0, 2: 0, 3: 0, 4: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.freedom_data = self.freedom_data.assign(strong_leader = self.freedom_data.E114.map({1: 0, 2: 0.33, 3: 0.66, 4: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.freedom_data = self.freedom_data.assign(army_rule = self.freedom_data.E116.map({1: 0, 2: 0.33, 3: 0.66, 4: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.freedom_data = self.freedom_data.assign(democratic_system = self.freedom_data.E117.map({1: 1, 2: 0.66, 3: 0.33, 4: 0, -1: 0.5, -2: None, -4: None, -5: None}))
                
    def recoding_socialism(self):
        self.socialism_data = self.socialism_data.assign(income_equality = self.socialism_data.E035.map({1: 1, 2: 1, 3: 0.75, 4: 0.75, 5: 0.5, 6: 0.5, 7: 0.25, 8: 0.25, 9: 0, 10: 0, -1: 0.5, -2: None, -4: None, -5: None}))
        self.socialism_data = self.socialism_data.assign(state_ownership = self.socialism_data.E036.map({1: 0, 2: 0, 3: 0.25, 4: 0.25, 5: 0.5, 6: 0.5, 7: 0.75, 8: 0.75, 9: 1, 10: 1, -1: 0.5, -2: None, -4: None, -5: None}))        
        self.socialism_data = self.socialism_data.assign(government_responsibility = self.socialism_data.E037.map({1: 1, 2: 1, 3: 0.75, 4: 0.75, 5: 0.5, 6: 0.5, 7: 0.25, 8: 0.25, 9: 0, 10: 0, -1: 0.5, -2: None, -4: None, -5: None}))        
        self.socialism_data = self.socialism_data.assign(competition_harmful = self.socialism_data.E039.map({1: 0, 2: 0, 3: 0.25, 4: 0.25, 5: 0.5, 6: 0.5, 7: 0.75, 8: 0.75, 9: 1, 10: 1, -1: 0.5, -2: None, -4: None, -5: None}))                
        
    def recoding_family(self):
        self.family_data = self.family_data.assign(justifiable_homosexuality = self.family_data.F118.map({1: 0, 2: 0, 3: 0.25, 4: 0.25, 5: 0.5, 6: 0.5, 7: 0.75, 8: 0.75, 9: 1, 10: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.family_data = self.family_data.assign(justifiable_prostitution = self.family_data.F119.map({1: 0, 2: 0, 3: 0.25, 4: 0.25, 5: 0.5, 6: 0.5, 7: 0.75, 8: 0.75, 9: 1, 10: 1, -1: 0.5, -2: None, -4: None, -5: None}))  
        self.family_data = self.family_data.assign(justifiable_abortion = self.family_data.F120.map({1: 0, 2: 0, 3: 0.25, 4: 0.25, 5: 0.5, 6: 0.5, 7: 0.75, 8: 0.75, 9: 1, 10: 1, -1: 0.5, -2: None, -4: None, -5: None}))  
        self.family_data = self.family_data.assign(justifiable_divorce = self.family_data.F121.map({1: 0, 2: 0, 3: 0.25, 4: 0.25, 5: 0.5, 6: 0.5, 7: 0.75, 8: 0.75, 9: 1, 10: 1, -1: 0.5, -2: None, -4: None, -5: None}))          
        
    def recoding_ethnicity(self):
        self.ethnicity_data = self.ethnicity_data.assign(neighbors_race = self.ethnicity_data.A124_02.map({0: 1, 1: 0, -1: 0.5, -2: None, -4: None, -5: None}))
        self.ethnicity_data = self.ethnicity_data.assign(neighbors_immigrants = self.ethnicity_data.A124_06.map({0: 1, 1: 0, -1: 0.5, -2: None, -4: None, -5: None}))
        self.ethnicity_data = self.ethnicity_data.assign(imigrant_jobs = self.ethnicity_data.C002.map({1: 0, 2: 1, 3: 0.5, -1: 0.5, -2: None, -4: None, -5: None}))        
        
    def recoding_gender(self):
        self.gender_data = self.gender_data.assign(men_leaders = self.gender_data.D059.map({1: 0, 2: 0.33, 3: 0.66, 4: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.gender_data = self.gender_data.assign(men_jobs = self.gender_data.C001.map({1: 0, 2: 1, 3: 0.5, -1: 0.5, -2: None, -4: None, -5: None}))
        self.gender_data = self.gender_data.assign(university_boy = self.gender_data.D060.map({1: 0, 2: 0.33, 3: 0.66, 4: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        
    def recoding_nationalism(self):
        self.nationalism_data = self.nationalism_data.assign(willing_to_fight = self.nationalism_data.E012.map({0: 0, 1: 1, -1: 0.5, -2: None, -4: None, -5: None}))        
        self.nationalism_data = self.nationalism_data.assign(national_pride = self.nationalism_data.G006.map({1: 1, 2: 0.66, 3: 0.33, 4: 0, -1: 0.5, -2: None, -4: None, -5: None}))                
        
    def recoding_religiosity(self):
        self.religiosity_data = self.religiosity_data.assign(important_in_life = self.religiosity_data.A006.map({1: 1, 2: 0.66, 3: 0.33, 4: 0, -1: 0.5, -2: None, -4: None, -5: None}))
        self.religiosity_data = self.religiosity_data.assign(child_faith = self.religiosity_data.A040.map({0: 0, 1: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.religiosity_data = self.religiosity_data.assign(importance_of_god = self.religiosity_data.F063.map({1: 0, 2: 0, 3: 0.25, 4: 0.25, 5: 0.5, 6: 0.5, 7: 0.75, 8: 0.75, 9: 1, 10: 1, -1: 0.5, -2: None, -4: None, -5: None}))
        self.religiosity_data = self.religiosity_data.assign(religious_attendance = self.religiosity_data.F028.map({1: 1, 2: 1, 3: 0.75, 4: 0.5, 5: 0.25, 6: 0, 7: 0, -1: 0.5, -2: None, -4: None, -5: None}))        
        self.religiosity_data = self.religiosity_data.assign(religious_person = self.religiosity_data.F034.map({1: 1, 2: 0.5, 3: 1, -1: 0.5, -2: None, -4: None, -5: None}))

    def subindices_freedom(self):
        self.freedom_data = self.freedom_data.assign(child_qualities = (self.freedom_data.child_independence + self.freedom_data.child_imagination + self.freedom_data.child_obedience)/3)
        self.freedom_data = self.freedom_data.assign(social_goals = (self.freedom_data.aim_of_country + self.freedom_data.aim_of_respondent)/2)
        self.freedom_data = self.freedom_data.assign(political_systems = (self.freedom_data.strong_leader + self.freedom_data.army_rule + self.freedom_data.democratic_system)/3)
        
    def building_indices(self):
        self.freedom_data = self.freedom_data.assign(freedom_index = round((self.freedom_data.child_qualities + self.freedom_data.respect_authority + self.freedom_data.social_goals + self.freedom_data.political_systems)/4, 2))
        self.socialism_data = self.socialism_data.assign(socialism_index = round((self.socialism_data.income_equality + self.socialism_data.state_ownership + self.socialism_data.government_responsibility + self.socialism_data.competition_harmful)/4, 2))
        self.family_data = self.family_data.assign(family_index = round((self.family_data.justifiable_homosexuality + self.family_data.justifiable_prostitution + self.family_data.justifiable_abortion + self.family_data.justifiable_divorce)/4, 2))
        self.ethnicity_data = self.ethnicity_data.assign(ethnicity_index = round((self.ethnicity_data.neighbors_race + self.ethnicity_data.neighbors_immigrants + self.ethnicity_data.imigrant_jobs)/3, 2))
        self.gender_data = self.gender_data.assign(gender_index = round((self.gender_data.men_leaders + self.gender_data.men_jobs + self.gender_data.university_boy)/3, 2))
        self.nationalism_data = self.nationalism_data.assign(nationalism_index = round((self.nationalism_data.willing_to_fight + self.nationalism_data.national_pride)/2, 2))
        self.religiosity_data = self.religiosity_data.assign(religiosity_index = round((self.religiosity_data.important_in_life + self.religiosity_data.child_faith + self.religiosity_data.religious_attendance + self.religiosity_data.importance_of_god + self.religiosity_data.religious_person)/5, 2))
        
    def index_frame(self):
        self.final_frame = self.demographics_data[['country', 'gender', 'education', 'social_class', 'income', 'urban']]
        self.political_orientation_indices = ["self.freedom_data[['freedom_index']]",
        "self.socialism_data[['socialism_index']]",
        "self.family_data[['family_index']]",
        "self.ethnicity_data[['ethnicity_index']]",
        "self.gender_data[['gender_index']]",
        "self.nationalism_data[['nationalism_index']]",
        "self.religiosity_data[['religiosity_index']]"]
        for x in self.political_orientation_indices:
            exec(f'self.final_frame = self.final_frame.join({x})')

    def data_saver(self):
        self.final_frame.to_csv('./individual_level_processed_data/final_frame.csv', sep=',', index=False, encoding='utf-8')

## Instantiating the class

In [6]:
IndividualLevelIndexBuilder = IndividualLevelIndexBuilding()

## Caling the methods

In [7]:
IndividualLevelIndexBuilder.loading_each_dataset()

In [54]:
IndividualLevelIndexBuilder.recoding_demographics()

In [55]:
IndividualLevelIndexBuilder.recoding_freedom()

In [56]:
IndividualLevelIndexBuilder.recoding_socialism()

In [57]:
IndividualLevelIndexBuilder.recoding_family()

In [58]:
IndividualLevelIndexBuilder.recoding_ethnicity()

In [59]:
IndividualLevelIndexBuilder.recoding_gender()

In [60]:
IndividualLevelIndexBuilder.recoding_nationalism()

In [61]:
IndividualLevelIndexBuilder.recoding_religiosity()

In [62]:
IndividualLevelIndexBuilder.subindices_freedom()

In [63]:
IndividualLevelIndexBuilder.building_indices()

In [64]:
IndividualLevelIndexBuilder.index_frame()

In [66]:
IndividualLevelIndexBuilder.data_saver()

# The results

## The loading_each_dataset() method, the nine recoding methods, the subindices_freedom() method and the building_indices() method

#### Freedom data

In [8]:
IndividualLevelIndexBuilder.freedom_data

A029  A034  A040  A042  E018  E001  E003  E114  E116  E117
0          0     0     0     1     2    -1    -1    -1    -1     1
1          0     0     0     1     2    -1    -1    -1    -1    -1
2          0     0     0     1     2    -1    -1    -1    -1    -1
3          1     1     0     1     2    -1    -1     4     4     1
4          0     0     0     1     2     1    -1     3     4     2
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
675298     1     0     1     1     1    -4     1     1     2     2
675299     0     0     1     0     1    -4     1     2     2     2
675300     1     0     1     1     1    -4     3    -1     1     1
675301     0     0     0     1     1    -4     2    -1     1     1
675302     0     0     1     0     3    -4     1    -1    -1    -1

[675303 rows x 10 columns]

In [9]:
IndividualLevelIndexBuilder.freedom_data.A029.unique()

array([ 0,  1, -2, -1, -4, -5], dtype=int64)

In [10]:
IndividualLevelIndexBuilder.freedom_data.A034.unique()

array([ 0,  1, -2, -1, -4, -5], dtype=int64)

In [11]:
IndividualLevelIndexBuilder.freedom_data.A040.unique()

array([ 0,  1, -2, -1, -4, -5], dtype=int64)

In [12]:
IndividualLevelIndexBuilder.freedom_data.A042.unique()

array([ 1,  0, -2, -1, -4, -5], dtype=int64)

In [13]:
IndividualLevelIndexBuilder.freedom_data.E018.unique()

array([ 2,  1,  3, -1, -2, -5, -4], dtype=int64)

In [14]:
IndividualLevelIndexBuilder.freedom_data.E001.unique()

array([-1,  1,  3,  2,  4, -2, -4, -5], dtype=int64)

In [15]:
IndividualLevelIndexBuilder.freedom_data.E003.unique()

array([-1,  1,  3,  4,  2, -2, -4, -5], dtype=int64)

In [16]:
IndividualLevelIndexBuilder.freedom_data.E114.unique()

array([-1,  4,  3,  1,  2, -2, -4, -5], dtype=int64)

In [17]:
IndividualLevelIndexBuilder.freedom_data.E116.unique()

array([-1,  4,  1,  3,  2, -2, -4, -5], dtype=int64)

In [18]:
IndividualLevelIndexBuilder.freedom_data.E117.unique()

array([ 1, -1,  2,  4,  3, -2, -4, -5], dtype=int64)

#### Socialism data

In [19]:
IndividualLevelIndexBuilder.socialism_data

E035  E036  E037  E039
0          7     3     4     3
1          7     3    10     2
2          7     1     9    -1
3          9     2     8     3
4          4     6     8     6
...      ...   ...   ...   ...
675298     5    10     5     4
675299    10    10    10     5
675300    10    10    10     5
675301     1    -1    10     7
675302     5    10     5     7

[675303 rows x 4 columns]

In [20]:
IndividualLevelIndexBuilder.socialism_data.E035.unique()

array([ 7,  9,  4,  2,  5,  6, 10, -1,  1,  3,  8, -2, -4, -5],
      dtype=int64)

In [21]:
IndividualLevelIndexBuilder.socialism_data.E036.unique()

array([ 3,  1,  2,  6, -1,  5, 10,  8,  7,  4,  9, -2, -4, -5],
      dtype=int64)

In [22]:
IndividualLevelIndexBuilder.socialism_data.E037.unique()

array([ 4, 10,  9,  8,  3,  7,  5,  2,  6,  1, -1, -2, -4, -5],
      dtype=int64)

In [23]:
IndividualLevelIndexBuilder.socialism_data.E039.unique()

array([ 3,  2, -1,  6,  5,  1,  4,  7, 10,  9,  8, -4, -2, -5],
      dtype=int64)

#### Family_data

In [24]:
IndividualLevelIndexBuilder.family_data

F118  F119  F120  F121
0         -1     1    -1     1
1          1     1     1     1
2         -1     1     1     1
3          4     4    10     6
4          1     1     1     3
...      ...   ...   ...   ...
675298     2     5     1     4
675299     1    10     1     5
675300     7     5     5    10
675301     1     1     1     1
675302     5     2     1     1

[675303 rows x 4 columns]

In [25]:
IndividualLevelIndexBuilder.family_data.F118.unique()

array([-1,  1,  4,  6,  3,  2,  7,  5,  9,  8, 10, -2, -4, -5],
      dtype=int64)

In [26]:
IndividualLevelIndexBuilder.family_data.F119.unique()

array([ 1,  4,  3,  2, -1,  5,  7,  6,  9,  8, 10, -4, -2, -5],
      dtype=int64)

In [27]:
IndividualLevelIndexBuilder.family_data.F120.unique()

array([-1,  1, 10,  3,  6,  5,  2,  4,  9,  7,  8, -2, -4, -5],
      dtype=int64)

In [28]:
IndividualLevelIndexBuilder.family_data.F121.unique()

array([ 1,  6,  3,  4,  2,  5,  8, 10,  7,  9, -1, -2, -4, -5],
      dtype=int64)

#### Ethnicity data

In [32]:
IndividualLevelIndexBuilder.ethnicity_data

A124_02  A124_06  C002
0             1        0     1
1             0        0     1
2             0        0     1
3             0        0     3
4             1        1     1
...         ...      ...   ...
675298        0        0     1
675299        0        0     1
675300        1        1     1
675301        0        1     1
675302        0        1     1

[675303 rows x 3 columns]

In [29]:
IndividualLevelIndexBuilder.ethnicity_data.A124_02.unique()

array([ 1,  0, -1, -2, -4, -5], dtype=int64)

In [30]:
IndividualLevelIndexBuilder.ethnicity_data.A124_06.unique()

array([ 0,  1, -1, -2, -4, -5], dtype=int64)

In [31]:
IndividualLevelIndexBuilder.ethnicity_data.C002.unique()

array([ 1,  3,  2, -1, -4, -2, -5], dtype=int64)

#### Gender data

In [33]:
IndividualLevelIndexBuilder.gender_data

D059  C001  D060
0          2     3     3
1         -1     1    -1
2         -1     1    -1
3          3     2     4
4          1     1     1
...      ...   ...   ...
675298    -4     2    -4
675299    -4     2    -4
675300    -4     2    -4
675301    -4     2    -4
675302    -4     2    -4

[675303 rows x 3 columns]

In [34]:
IndividualLevelIndexBuilder.gender_data.D059.unique()

array([ 2, -1,  3,  1,  4, -2, -4, -5], dtype=int64)

In [35]:
IndividualLevelIndexBuilder.gender_data.C001.unique()

array([ 3,  1,  2, -1, -2, -4, -5], dtype=int64)

In [36]:
IndividualLevelIndexBuilder.gender_data.D060.unique()

array([ 3, -1,  4,  1,  2, -2, -4, -5], dtype=int64)

#### Nationalism data

In [37]:
IndividualLevelIndexBuilder.nationalism_data

E012  G006
0          0     2
1         -1     2
2         -1     1
3          0     3
4          1     1
...      ...   ...
675298    -4    -3
675299    -4    -3
675300    -4    -3
675301    -4    -3
675302    -4    -3

[675303 rows x 2 columns]

In [38]:
IndividualLevelIndexBuilder.nationalism_data.E012.unique()

array([ 0, -1,  1, -4, -2, -3, -5], dtype=int64)

In [39]:
IndividualLevelIndexBuilder.nationalism_data.G006.unique()

array([ 2,  1,  3, -1, -3,  4, -2, -5, -4], dtype=int64)

#### Religiosity data

In [40]:
IndividualLevelIndexBuilder.religiosity_data

A006  A040  F063  F028  F034
0          2     0    10     8     1
1          3     0     5     4     1
2          2     0     6     6     1
3          4     0     8     8     3
4          3     0    10     8     1
...      ...   ...   ...   ...   ...
675298     1     1    10     4     1
675299     1     1    10     4     1
675300     1     1    10     1     1
675301     1     0    10     4     1
675302     1     1    10     4     1

[675303 rows x 5 columns]

In [41]:
IndividualLevelIndexBuilder.religiosity_data.A006.unique()

array([ 2,  3,  4,  1, -1, -2, -4, -5, -3], dtype=int64)

In [42]:
IndividualLevelIndexBuilder.religiosity_data.A040.unique()

array([ 0,  1, -2, -1, -4, -5], dtype=int64)

In [43]:
IndividualLevelIndexBuilder.religiosity_data.F063.unique()

array([10,  5,  6,  8,  4,  7,  1, -1,  9,  3,  2, -2, -4], dtype=int64)

In [44]:
IndividualLevelIndexBuilder.religiosity_data.F028.unique()

array([ 8,  4,  6,  7,  2,  3,  1, -1, -2,  5, -3, -4, -5], dtype=int64)

In [45]:
IndividualLevelIndexBuilder.religiosity_data.F034.unique()

array([ 1,  3,  2, -1, -2, -4, -5], dtype=int64)

#### Demographics data

In [46]:
IndividualLevelIndexBuilder.demographics_data

S003  X001  X003  X025  X045  X047_IVS  X049
0          8     2    18     6    -1         3     3
1          8     1    28     4     4         6     1
2          8     1    67    -3     4         7     1
3          8     2    33     7     2         9     4
4          8     1    38     6     5         3     4
...      ...   ...   ...   ...   ...       ...   ...
675298   915     2    24     5    -4         6    -5
675299   915     1    50     5    -4         4    -5
675300   915     2    23     5    -4        10    -5
675301   915     2    34     4    -4         9    -5
675302   915     1    51     6    -4         5    -5

[675303 rows x 7 columns]

In [47]:
IndividualLevelIndexBuilder.demographics_data.S003.unique()

array([  8,  12,  20,  31,  32,  36,  50,  51,  68,  70,  76, 100, 104,
       112, 124, 152, 156, 158, 170, 191, 196, 203, 214, 218, 222, 231,
       233, 246, 250, 268, 275, 276, 288, 300, 320, 332, 344, 348, 356,
       360, 364, 368, 376, 380, 392, 398, 400, 404, 410, 414, 417, 422,
       428, 434, 440, 446, 458, 462, 466, 484, 496, 498, 499, 504, 528,
       554, 558, 566, 578, 586, 604, 608, 616, 630, 634, 642, 643, 646,
       682, 688, 702, 703, 704, 705, 710, 716, 724, 752, 756, 762, 764,
       780, 788, 792, 800, 804, 807, 818, 826, 834, 840, 854, 858, 860,
       862, 887, 894, 909,  40,  56, 197, 208, 352, 372, 442, 470, 620,
       915], dtype=int64)

In [48]:
IndividualLevelIndexBuilder.demographics_data.X001.unique()

array([ 2,  1, -1, -2, -5, -4], dtype=int64)

In [49]:
IndividualLevelIndexBuilder.demographics_data.X003.unique()

array([ 18,  28,  67,  33,  38,  70,  19,  26,  61,  45,  76,  43,  65,
        57,  58,  49,  39,  66,  74,  40,  34,  44,  30,  55,  64,  36,
        37,  50,  54,  29,  42,  41,  53,  24,  21,  46,  23,  56,  20,
        52,  22,  32,  31,  47,  60,  71,  25,  72,  27,  35,  51,  62,
        48,  73,  63,  59,  79,  69,  68,  75,  81,  17,  80,  78,  77,
        -2,  82,  88,  87,  84,  86,  83,  90,  85,  89,  16,  91,  92,
        93,  94,  95,  15,  14,  98,  -5,  99,  97,  -1,  -4,  96, 102,
        13, 100, 103,  -3, 101, 108], dtype=int64)

In [50]:
IndividualLevelIndexBuilder.demographics_data.X025.unique()

array([ 6,  4, -3,  7,  2,  1,  8,  3,  5, -2, -1, -4, -5], dtype=int64)

In [51]:
IndividualLevelIndexBuilder.demographics_data.X045.unique()

array([-1,  4,  2,  5,  3,  1, -2, -4, -3, -5], dtype=int64)

In [52]:
IndividualLevelIndexBuilder.demographics_data.X047_IVS.unique()

array([ 3,  6,  7,  9,  5,  4,  1,  8,  2, 10, -1, -2, -4, -5, 11, -3],
      dtype=int64)

In [53]:
IndividualLevelIndexBuilder.demographics_data.X049.unique()

array([ 3,  1,  4,  7,  2,  5,  8,  6, -1, -4, -2, -5], dtype=int64)

## The index_frame() method

In [65]:
IndividualLevelIndexBuilder.final_frame

country  gender  education  social_class  income  urban  \
0             8     1.0        1.0          0.50    0.25   0.25   
1             8     0.0        0.5          0.25    0.50   0.00   
2             8     0.0        NaN          0.25    0.75   0.00   
3             8     1.0        1.0          0.75    1.00   0.25   
4             8     0.0        1.0          0.00    0.25   0.25   
...         ...     ...        ...           ...     ...    ...   
675298      915     1.0        0.5           NaN    0.50    NaN   
675299      915     0.0        0.5           NaN    0.25    NaN   
675300      915     1.0        0.5           NaN    1.00    NaN   
675301      915     1.0        0.5           NaN    1.00    NaN   
675302      915     0.0        1.0           NaN    0.50    NaN   

        freedom_index  socialism_index  family_index  ethnicity_index  \
0                0.42             0.38          0.25             0.33   
1                0.38             0.12          0.00             0.67   
2                0.38             0.19          0.12             0.67   
3                0.67             0.12          0.50             0.83   
4                0.38             0.50          0.06             0.00   
...               ...              ...           ...              ...   
675298            NaN             0.56          0.19             0.67   
675299            NaN             0.38          0.38             0.67   
675300            NaN             0.38          0.69             0.00   
675301            NaN             0.56          0.00             0.33   
675302            NaN             0.69          0.12             0.33   

        gender_index  nationalism_index  religiosity_index  
0               0.50               0.33                NaN  
1               0.33               0.58               0.47  
2               0.33               0.75               0.43  
3               0.89               0.16                NaN  
4               0.00               1.00                NaN  
...              ...                ...                ...  
675298           NaN                NaN               0.90  
675299           NaN                NaN               0.90  
675300           NaN                NaN               1.00  
675301           NaN                NaN               0.70  
675302           NaN                NaN               0.90  

[675303 rows x 13 columns]

## The data_saver() method

In [67]:
saved_frame = pd.read_csv('final_frame.csv')

In [68]:
saved_frame

country  gender  education  social_class  income  urban  \
0             8     1.0        1.0          0.50    0.25   0.25   
1             8     0.0        0.5          0.25    0.50   0.00   
2             8     0.0        NaN          0.25    0.75   0.00   
3             8     1.0        1.0          0.75    1.00   0.25   
4             8     0.0        1.0          0.00    0.25   0.25   
...         ...     ...        ...           ...     ...    ...   
675298      915     1.0        0.5           NaN    0.50    NaN   
675299      915     0.0        0.5           NaN    0.25    NaN   
675300      915     1.0        0.5           NaN    1.00    NaN   
675301      915     1.0        0.5           NaN    1.00    NaN   
675302      915     0.0        1.0           NaN    0.50    NaN   

        freedom_index  socialism_index  family_index  ethnicity_index  \
0                0.42             0.38          0.25             0.33   
1                0.38             0.12          0.00             0.67   
2                0.38             0.19          0.12             0.67   
3                0.67             0.12          0.50             0.83   
4                0.38             0.50          0.06             0.00   
...               ...              ...           ...              ...   
675298            NaN             0.56          0.19             0.67   
675299            NaN             0.38          0.38             0.67   
675300            NaN             0.38          0.69             0.00   
675301            NaN             0.56          0.00             0.33   
675302            NaN             0.69          0.12             0.33   

        gender_index  nationalism_index  religiosity_index  
0               0.50               0.33                NaN  
1               0.33               0.58               0.47  
2               0.33               0.75               0.43  
3               0.89               0.16                NaN  
4               0.00               1.00                NaN  
...              ...                ...                ...  
675298           NaN                NaN               0.90  
675299           NaN                NaN               0.90  
675300           NaN                NaN               1.00  
675301           NaN                NaN               0.70  
675302           NaN                NaN               0.90  

[675303 rows x 13 columns]